"""REST API routes for Kundali backend."""
from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from fastapi import APIRouter, Depends, HTTPException, Path, Query, status
from sqlalchemy.orm import Session

from backend.api.schemas import (
    AnalyticsSummary,
    BirthDataInput,
    ChartComputationResponse,
    ChartData,
    ChartMetadata,
    PlanetPosition,
    ReportPayload,
    ReportSection,
)
from backend.db.database import get_session
from backend.db import models

router = APIRouter(prefix="/api", tags=["Charts", "Reports", "Analytics"])


@router.post(
    "/charts/generate",
    response_model=ChartComputationResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a natal or transit chart",
)
async def generate_chart(
    payload: BirthDataInput, session: Session = Depends(get_session)
) -> ChartComputationResponse:
    """Generate a chart for the supplied birth data."""

    # Placeholder logic; integration with actual computation engine required.
    chart_id = uuid4()
    chart = models.SavedChart(
        id=chart_id,
        user_id=None,
        chart_type="natal",
        generated_at=datetime.utcnow(),
        input_payload=payload.model_dump(),
        chart_payload={},
    )
    session.add(chart)
    session.commit()
    session.refresh(chart)

    response = ChartComputationResponse(
        chart=ChartData(
            id=chart_id,
            metadata=ChartMetadata(
                chart_type="natal",
                computation_time=datetime.utcnow(),
                algorithm_version="v1",
                source_url=None,
            ),
            planet_positions=[
                PlanetPosition(
                    planet="Sun",
                    sign="Aries",
                    house=1,
                    degree=0.0,
                    retrograde=False,
                )
            ],
            house_positions=[],
            aspects=[],
        ),
        generated_report_id=None,
    )
    return response


@router.get(
    "/reports/{report_id}",
    response_model=ReportPayload,
    summary="Retrieve a generated report",
)
async def get_report(
    report_id: UUID = Path(..., description="Identifier of the requested report"),
    session: Session = Depends(get_session),
) -> ReportPayload:
    """Fetch a persisted report by identifier."""

    chart = session.get(models.SavedChart, report_id)
    if chart is None:
        raise HTTPException(status_code=404, detail="Report not found")

    return ReportPayload(
        id=report_id,
        chart_id=report_id,
        generated_at=chart.generated_at,
        sections=[
            ReportSection(
                title="Sample Report",
                summary="Placeholder summary",
                content="Narrative content generated by the reporting engine.",
            )
        ],
        shareable_url=None,
    )


@router.get(
    "/analytics",
    response_model=AnalyticsSummary,
    summary="Retrieve analytics summary for chart generation",
)
async def get_analytics(
    start_date: datetime = Query(..., description="Start of analytics window"),
    end_date: datetime = Query(..., description="End of analytics window"),
    session: Session = Depends(get_session),
) -> AnalyticsSummary:
    """Return aggregated analytics for the requested window."""

    if start_date > end_date:
        raise HTTPException(status_code=400, detail="start_date must be before end_date")

    total_charts = session.query(models.SavedChart).count()
    total_reports = session.query(models.OrderHistory).count()

    return AnalyticsSummary(
        total_charts=total_charts,
        total_reports=total_reports,
        breakdowns=[],
    )


__all__ = ["router"]
